POST http://localhost:8080/calc/calc
Content-Type: application/json
apiKey: apiKey:3917

{
  "num1": 843,
  "num2": 9,
  "type": "div"
  }

###

GET http://localhost:8080/calc/history
apiKey: apiKey:3917

###

GET http://localhost:8080/calc/history/sort/div

###

POST http://localhost:8080/registr
Content-Type: application/json

{
  "name": "Test",
  "login": "test",
  "password": "test"
}

###

POST http://localhost:8080/auth
Content-Type: application/json

{
  "login": "test",
  "password": "test"
}
