POST http://localhost:8080/calc/calc
Content-Type: application/json

{
  "num1": 81,
  "num2": 9,
  "type": "div"
  }

###

GET http://localhost:8080/calc/history

###

GET http://localhost:8080/calc/history/sort/div

###

POST http://localhost:8080/registr
Content-Type: application/json

{
  "name": "Test",
  "login": "test",
  "password": "test"
}